/*
 * OpenMeteoApiNet - A C# library for accessing the Open-Meteo API.
 * 
 * (C) Eric J. Drewitz 2026
 */

namespace OpenMeteoApiNet.Variables.HourlyData.GEM_ENS
{
    public class gemENSParams
    {
        public string?[]? time { get; set; }
        public double?[]? temperature_2m { get; set; }
        public double?[]? temperature_2m_member01 { get; set; }
        public double?[]? temperature_2m_member02 { get; set; }
        public double?[]? temperature_2m_member03 { get; set; }
        public double?[]? temperature_2m_member04 { get; set; }
        public double?[]? temperature_2m_member05 { get; set; }
        public double?[]? temperature_2m_member06 { get; set; }
        public double?[]? temperature_2m_member07 { get; set; }
        public double?[]? temperature_2m_member08 { get; set; }
        public double?[]? temperature_2m_member09 { get; set; }
        public double?[]? temperature_2m_member10 { get; set; }
        public double?[]? temperature_2m_member11 { get; set; }
        public double?[]? temperature_2m_member12 { get; set; }
        public double?[]? temperature_2m_member13 { get; set; }
        public double?[]? temperature_2m_member14 { get; set; }
        public double?[]? temperature_2m_member15 { get; set; }
        public double?[]? temperature_2m_member16 { get; set; }
        public double?[]? temperature_2m_member17 { get; set; }
        public double?[]? temperature_2m_member18 { get; set; }
        public double?[]? temperature_2m_member19 { get; set; }
        public double?[]? temperature_2m_member20 { get; set; }
        public double?[]? relative_humidity_2m { get; set; }
        public double?[]? relative_humidity_2m_member01 { get; set; }
        public double?[]? relative_humidity_2m_member02 { get; set; }
        public double?[]? relative_humidity_2m_member03 { get; set; }
        public double?[]? relative_humidity_2m_member04 { get; set; }
        public double?[]? relative_humidity_2m_member05 { get; set; }
        public double?[]? relative_humidity_2m_member06 { get; set; }
        public double?[]? relative_humidity_2m_member07 { get; set; }
        public double?[]? relative_humidity_2m_member08 { get; set; }
        public double?[]? relative_humidity_2m_member09 { get; set; }
        public double?[]? relative_humidity_2m_member10 { get; set; }
        public double?[]? relative_humidity_2m_member11 { get; set; }
        public double?[]? relative_humidity_2m_member12 { get; set; }
        public double?[]? relative_humidity_2m_member13 { get; set; }
        public double?[]? relative_humidity_2m_member14 { get; set; }
        public double?[]? relative_humidity_2m_member15 { get; set; }
        public double?[]? relative_humidity_2m_member16 { get; set; }
        public double?[]? relative_humidity_2m_member17 { get; set; }
        public double?[]? relative_humidity_2m_member18 { get; set; }
        public double?[]? relative_humidity_2m_member19 { get; set; }
        public double?[]? relative_humidity_2m_member20 { get; set; }
        public double?[]? dew_point_2m { get; set; }
        public double?[]? dew_point_2m_member01 { get; set; }
        public double?[]? dew_point_2m_member02 { get; set; }
        public double?[]? dew_point_2m_member03 { get; set; }
        public double?[]? dew_point_2m_member04 { get; set; }
        public double?[]? dew_point_2m_member05 { get; set; }
        public double?[]? dew_point_2m_member06 { get; set; }
        public double?[]? dew_point_2m_member07 { get; set; }
        public double?[]? dew_point_2m_member08 { get; set; }
        public double?[]? dew_point_2m_member09 { get; set; }
        public double?[]? dew_point_2m_member10 { get; set; }
        public double?[]? dew_point_2m_member11 { get; set; }
        public double?[]? dew_point_2m_member12 { get; set; }
        public double?[]? dew_point_2m_member13 { get; set; }
        public double?[]? dew_point_2m_member14 { get; set; }
        public double?[]? dew_point_2m_member15 { get; set; }
        public double?[]? dew_point_2m_member16 { get; set; }
        public double?[]? dew_point_2m_member17 { get; set; }
        public double?[]? dew_point_2m_member18 { get; set; }
        public double?[]? dew_point_2m_member19 { get; set; }
        public double?[]? dew_point_2m_member20 { get; set; }
        public double?[]? apparent_temperature { get; set; }
        public double?[]? apparent_temperature_member01 { get; set; }
        public double?[]? apparent_temperature_member02 { get; set; }
        public double?[]? apparent_temperature_member03 { get; set; }
        public double?[]? apparent_temperature_member04 { get; set; }
        public double?[]? apparent_temperature_member05 { get; set; }
        public double?[]? apparent_temperature_member06 { get; set; }
        public double?[]? apparent_temperature_member07 { get; set; }
        public double?[]? apparent_temperature_member08 { get; set; }
        public double?[]? apparent_temperature_member09 { get; set; }
        public double?[]? apparent_temperature_member10 { get; set; }
        public double?[]? apparent_temperature_member11 { get; set; }
        public double?[]? apparent_temperature_member12 { get; set; }
        public double?[]? apparent_temperature_member13 { get; set; }
        public double?[]? apparent_temperature_member14 { get; set; }
        public double?[]? apparent_temperature_member15 { get; set; }
        public double?[]? apparent_temperature_member16 { get; set; }
        public double?[]? apparent_temperature_member17 { get; set; }
        public double?[]? apparent_temperature_member18 { get; set; }
        public double?[]? apparent_temperature_member19 { get; set; }
        public double?[]? apparent_temperature_member20 { get; set; }
        public double?[]? precipitation { get; set; }
        public double?[]? precipitation_member01 { get; set; }
        public double?[]? precipitation_member02 { get; set; }
        public double?[]? precipitation_member03 { get; set; }
        public double?[]? precipitation_member04 { get; set; }
        public double?[]? precipitation_member05 { get; set; }
        public double?[]? precipitation_member06 { get; set; }
        public double?[]? precipitation_member07 { get; set; }
        public double?[]? precipitation_member08 { get; set; }
        public double?[]? precipitation_member09 { get; set; }
        public double?[]? precipitation_member10 { get; set; }
        public double?[]? precipitation_member11 { get; set; }
        public double?[]? precipitation_member12 { get; set; }
        public double?[]? precipitation_member13 { get; set; }
        public double?[]? precipitation_member14 { get; set; }
        public double?[]? precipitation_member15 { get; set; }
        public double?[]? precipitation_member16 { get; set; }
        public double?[]? precipitation_member17 { get; set; }
        public double?[]? precipitation_member18 { get; set; }
        public double?[]? precipitation_member19 { get; set; }
        public double?[]? precipitation_member20 { get; set; }
        public double?[]? rain { get; set; }
        public double?[]? rain_member01 { get; set; }
        public double?[]? rain_member02 { get; set; }
        public double?[]? rain_member03 { get; set; }
        public double?[]? rain_member04 { get; set; }
        public double?[]? rain_member05 { get; set; }
        public double?[]? rain_member06 { get; set; }
        public double?[]? rain_member07 { get; set; }
        public double?[]? rain_member08 { get; set; }
        public double?[]? rain_member09 { get; set; }
        public double?[]? rain_member10 { get; set; }
        public double?[]? rain_member11 { get; set; }
        public double?[]? rain_member12 { get; set; }
        public double?[]? rain_member13 { get; set; }
        public double?[]? rain_member14 { get; set; }
        public double?[]? rain_member15 { get; set; }
        public double?[]? rain_member16 { get; set; }
        public double?[]? rain_member17 { get; set; }
        public double?[]? rain_member18 { get; set; }
        public double?[]? rain_member19 { get; set; }
        public double?[]? rain_member20 { get; set; }
        public double?[]? snowfall { get; set; }
        public double?[]? snowfall_member01 { get; set; }
        public double?[]? snowfall_member02 { get; set; }
        public double?[]? snowfall_member03 { get; set; }
        public double?[]? snowfall_member04 { get; set; }
        public double?[]? snowfall_member05 { get; set; }
        public double?[]? snowfall_member06 { get; set; }
        public double?[]? snowfall_member07 { get; set; }
        public double?[]? snowfall_member08 { get; set; }
        public double?[]? snowfall_member09 { get; set; }
        public double?[]? snowfall_member10 { get; set; }
        public double?[]? snowfall_member11 { get; set; }
        public double?[]? snowfall_member12 { get; set; }
        public double?[]? snowfall_member13 { get; set; }
        public double?[]? snowfall_member14 { get; set; }
        public double?[]? snowfall_member15 { get; set; }
        public double?[]? snowfall_member16 { get; set; }
        public double?[]? snowfall_member17 { get; set; }
        public double?[]? snowfall_member18 { get; set; }
        public double?[]? snowfall_member19 { get; set; }
        public double?[]? snowfall_member20 { get; set; }
        public double?[]? snow_depth { get; set; }
        public double?[]? snow_depth_member01 { get; set; }
        public double?[]? snow_depth_member02 { get; set; }
        public double?[]? snow_depth_member03 { get; set; }
        public double?[]? snow_depth_member04 { get; set; }
        public double?[]? snow_depth_member05 { get; set; }
        public double?[]? snow_depth_member06 { get; set; }
        public double?[]? snow_depth_member07 { get; set; }
        public double?[]? snow_depth_member08 { get; set; }
        public double?[]? snow_depth_member09 { get; set; }
        public double?[]? snow_depth_member10 { get; set; }
        public double?[]? snow_depth_member11 { get; set; }
        public double?[]? snow_depth_member12 { get; set; }
        public double?[]? snow_depth_member13 { get; set; }
        public double?[]? snow_depth_member14 { get; set; }
        public double?[]? snow_depth_member15 { get; set; }
        public double?[]? snow_depth_member16 { get; set; }
        public double?[]? snow_depth_member17 { get; set; }
        public double?[]? snow_depth_member18 { get; set; }
        public double?[]? snow_depth_member19 { get; set; }
        public double?[]? snow_depth_member20 { get; set; }
        public double?[]? weather_code { get; set; }
        public double?[]? weather_code_member01 { get; set; }
        public double?[]? weather_code_member02 { get; set; }
        public double?[]? weather_code_member03 { get; set; }
        public double?[]? weather_code_member04 { get; set; }
        public double?[]? weather_code_member05 { get; set; }
        public double?[]? weather_code_member06 { get; set; }
        public double?[]? weather_code_member07 { get; set; }
        public double?[]? weather_code_member08 { get; set; }
        public double?[]? weather_code_member09 { get; set; }
        public double?[]? weather_code_member10 { get; set; }
        public double?[]? weather_code_member11 { get; set; }
        public double?[]? weather_code_member12 { get; set; }
        public double?[]? weather_code_member13 { get; set; }
        public double?[]? weather_code_member14 { get; set; }
        public double?[]? weather_code_member15 { get; set; }
        public double?[]? weather_code_member16 { get; set; }
        public double?[]? weather_code_member17 { get; set; }
        public double?[]? weather_code_member18 { get; set; }
        public double?[]? weather_code_member19 { get; set; }
        public double?[]? weather_code_member20 { get; set; }
        public double?[]? pressure_msl { get; set; }
        public double?[]? pressure_msl_member01 { get; set; }
        public double?[]? pressure_msl_member02 { get; set; }
        public double?[]? pressure_msl_member03 { get; set; }
        public double?[]? pressure_msl_member04 { get; set; }
        public double?[]? pressure_msl_member05 { get; set; }
        public double?[]? pressure_msl_member06 { get; set; }
        public double?[]? pressure_msl_member07 { get; set; }
        public double?[]? pressure_msl_member08 { get; set; }
        public double?[]? pressure_msl_member09 { get; set; }
        public double?[]? pressure_msl_member10 { get; set; }
        public double?[]? pressure_msl_member11 { get; set; }
        public double?[]? pressure_msl_member12 { get; set; }
        public double?[]? pressure_msl_member13 { get; set; }
        public double?[]? pressure_msl_member14 { get; set; }
        public double?[]? pressure_msl_member15 { get; set; }
        public double?[]? pressure_msl_member16 { get; set; }
        public double?[]? pressure_msl_member17 { get; set; }
        public double?[]? pressure_msl_member18 { get; set; }
        public double?[]? pressure_msl_member19 { get; set; }
        public double?[]? pressure_msl_member20 { get; set; }
        public double?[]? cloud_cover { get; set; }
        public double?[]? cloud_cover_member01 { get; set; }
        public double?[]? cloud_cover_member02 { get; set; }
        public double?[]? cloud_cover_member03 { get; set; }
        public double?[]? cloud_cover_member04 { get; set; }
        public double?[]? cloud_cover_member05 { get; set; }
        public double?[]? cloud_cover_member06 { get; set; }
        public double?[]? cloud_cover_member07 { get; set; }
        public double?[]? cloud_cover_member08 { get; set; }
        public double?[]? cloud_cover_member09 { get; set; }
        public double?[]? cloud_cover_member10 { get; set; }
        public double?[]? cloud_cover_member11 { get; set; }
        public double?[]? cloud_cover_member12 { get; set; }
        public double?[]? cloud_cover_member13 { get; set; }
        public double?[]? cloud_cover_member14 { get; set; }
        public double?[]? cloud_cover_member15 { get; set; }
        public double?[]? cloud_cover_member16 { get; set; }
        public double?[]? cloud_cover_member17 { get; set; }
        public double?[]? cloud_cover_member18 { get; set; }
        public double?[]? cloud_cover_member19 { get; set; }
        public double?[]? cloud_cover_member20 { get; set; }
        public double?[]? surface_pressure { get; set; }
        public double?[]? surface_pressure_member01 { get; set; }
        public double?[]? surface_pressure_member02 { get; set; }
        public double?[]? surface_pressure_member03 { get; set; }
        public double?[]? surface_pressure_member04 { get; set; }
        public double?[]? surface_pressure_member05 { get; set; }
        public double?[]? surface_pressure_member06 { get; set; }
        public double?[]? surface_pressure_member07 { get; set; }
        public double?[]? surface_pressure_member08 { get; set; }
        public double?[]? surface_pressure_member09 { get; set; }
        public double?[]? surface_pressure_member10 { get; set; }
        public double?[]? surface_pressure_member11 { get; set; }
        public double?[]? surface_pressure_member12 { get; set; }
        public double?[]? surface_pressure_member13 { get; set; }
        public double?[]? surface_pressure_member14 { get; set; }
        public double?[]? surface_pressure_member15 { get; set; }
        public double?[]? surface_pressure_member16 { get; set; }
        public double?[]? surface_pressure_member17 { get; set; }
        public double?[]? surface_pressure_member18 { get; set; }
        public double?[]? surface_pressure_member19 { get; set; }
        public double?[]? surface_pressure_member20 { get; set; }
        public double?[]? et0_fao_evapotranspiration { get; set; }
        public double?[]? et0_fao_evapotranspiration_member01 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member02 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member03 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member04 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member05 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member06 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member07 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member08 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member09 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member10 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member11 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member12 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member13 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member14 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member15 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member16 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member17 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member18 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member19 { get; set; }
        public double?[]? et0_fao_evapotranspiration_member20 { get; set; }
        public double?[]? vapour_pressure_deficit { get; set; }
        public double?[]? vapour_pressure_deficit_member01 { get; set; }
        public double?[]? vapour_pressure_deficit_member02 { get; set; }
        public double?[]? vapour_pressure_deficit_member03 { get; set; }
        public double?[]? vapour_pressure_deficit_member04 { get; set; }
        public double?[]? vapour_pressure_deficit_member05 { get; set; }
        public double?[]? vapour_pressure_deficit_member06 { get; set; }
        public double?[]? vapour_pressure_deficit_member07 { get; set; }
        public double?[]? vapour_pressure_deficit_member08 { get; set; }
        public double?[]? vapour_pressure_deficit_member09 { get; set; }
        public double?[]? vapour_pressure_deficit_member10 { get; set; }
        public double?[]? vapour_pressure_deficit_member11 { get; set; }
        public double?[]? vapour_pressure_deficit_member12 { get; set; }
        public double?[]? vapour_pressure_deficit_member13 { get; set; }
        public double?[]? vapour_pressure_deficit_member14 { get; set; }
        public double?[]? vapour_pressure_deficit_member15 { get; set; }
        public double?[]? vapour_pressure_deficit_member16 { get; set; }
        public double?[]? vapour_pressure_deficit_member17 { get; set; }
        public double?[]? vapour_pressure_deficit_member18 { get; set; }
        public double?[]? vapour_pressure_deficit_member19 { get; set; }
        public double?[]? vapour_pressure_deficit_member20 { get; set; }
        public double?[]? wind_speed_10m { get; set; }
        public double?[]? wind_speed_10m_member01 { get; set; }
        public double?[]? wind_speed_10m_member02 { get; set; }
        public double?[]? wind_speed_10m_member03 { get; set; }
        public double?[]? wind_speed_10m_member04 { get; set; }
        public double?[]? wind_speed_10m_member05 { get; set; }
        public double?[]? wind_speed_10m_member06 { get; set; }
        public double?[]? wind_speed_10m_member07 { get; set; }
        public double?[]? wind_speed_10m_member08 { get; set; }
        public double?[]? wind_speed_10m_member09 { get; set; }
        public double?[]? wind_speed_10m_member10 { get; set; }
        public double?[]? wind_speed_10m_member11 { get; set; }
        public double?[]? wind_speed_10m_member12 { get; set; }
        public double?[]? wind_speed_10m_member13 { get; set; }
        public double?[]? wind_speed_10m_member14 { get; set; }
        public double?[]? wind_speed_10m_member15 { get; set; }
        public double?[]? wind_speed_10m_member16 { get; set; }
        public double?[]? wind_speed_10m_member17 { get; set; }
        public double?[]? wind_speed_10m_member18 { get; set; }
        public double?[]? wind_speed_10m_member19 { get; set; }
        public double?[]? wind_speed_10m_member20 { get; set; }
        public double?[]? wind_direction_10m { get; set; }
        public double?[]? wind_direction_10m_member01 { get; set; }
        public double?[]? wind_direction_10m_member02 { get; set; }
        public double?[]? wind_direction_10m_member03 { get; set; }
        public double?[]? wind_direction_10m_member04 { get; set; }
        public double?[]? wind_direction_10m_member05 { get; set; }
        public double?[]? wind_direction_10m_member06 { get; set; }
        public double?[]? wind_direction_10m_member07 { get; set; }
        public double?[]? wind_direction_10m_member08 { get; set; }
        public double?[]? wind_direction_10m_member09 { get; set; }
        public double?[]? wind_direction_10m_member10 { get; set; }
        public double?[]? wind_direction_10m_member11 { get; set; }
        public double?[]? wind_direction_10m_member12 { get; set; }
        public double?[]? wind_direction_10m_member13 { get; set; }
        public double?[]? wind_direction_10m_member14 { get; set; }
        public double?[]? wind_direction_10m_member15 { get; set; }
        public double?[]? wind_direction_10m_member16 { get; set; }
        public double?[]? wind_direction_10m_member17 { get; set; }
        public double?[]? wind_direction_10m_member18 { get; set; }
        public double?[]? wind_direction_10m_member19 { get; set; }
        public double?[]? wind_direction_10m_member20 { get; set; }
        public double?[]? temperature_850hPa { get; set; }
        public double?[]? temperature_850hPa_member01 { get; set; }
        public double?[]? temperature_850hPa_member02 { get; set; }
        public double?[]? temperature_850hPa_member03 { get; set; }
        public double?[]? temperature_850hPa_member04 { get; set; }
        public double?[]? temperature_850hPa_member05 { get; set; }
        public double?[]? temperature_850hPa_member06 { get; set; }
        public double?[]? temperature_850hPa_member07 { get; set; }
        public double?[]? temperature_850hPa_member08 { get; set; }
        public double?[]? temperature_850hPa_member09 { get; set; }
        public double?[]? temperature_850hPa_member10 { get; set; }
        public double?[]? temperature_850hPa_member11 { get; set; }
        public double?[]? temperature_850hPa_member12 { get; set; }
        public double?[]? temperature_850hPa_member13 { get; set; }
        public double?[]? temperature_850hPa_member14 { get; set; }
        public double?[]? temperature_850hPa_member15 { get; set; }
        public double?[]? temperature_850hPa_member16 { get; set; }
        public double?[]? temperature_850hPa_member17 { get; set; }
        public double?[]? temperature_850hPa_member18 { get; set; }
        public double?[]? temperature_850hPa_member19 { get; set; }
        public double?[]? temperature_850hPa_member20 { get; set; }
        public double?[]? temperature_500hPa { get; set; }
        public double?[]? temperature_500hPa_member01 { get; set; }
        public double?[]? temperature_500hPa_member02 { get; set; }
        public double?[]? temperature_500hPa_member03 { get; set; }
        public double?[]? temperature_500hPa_member04 { get; set; }
        public double?[]? temperature_500hPa_member05 { get; set; }
        public double?[]? temperature_500hPa_member06 { get; set; }
        public double?[]? temperature_500hPa_member07 { get; set; }
        public double?[]? temperature_500hPa_member08 { get; set; }
        public double?[]? temperature_500hPa_member09 { get; set; }
        public double?[]? temperature_500hPa_member10 { get; set; }
        public double?[]? temperature_500hPa_member11 { get; set; }
        public double?[]? temperature_500hPa_member12 { get; set; }
        public double?[]? temperature_500hPa_member13 { get; set; }
        public double?[]? temperature_500hPa_member14 { get; set; }
        public double?[]? temperature_500hPa_member15 { get; set; }
        public double?[]? temperature_500hPa_member16 { get; set; }
        public double?[]? temperature_500hPa_member17 { get; set; }
        public double?[]? temperature_500hPa_member18 { get; set; }
        public double?[]? temperature_500hPa_member19 { get; set; }
        public double?[]? temperature_500hPa_member20 { get; set; }
        public double?[]? geopotential_height_850hPa { get; set; }
        public double?[]? geopotential_height_850hPa_member01 { get; set; }
        public double?[]? geopotential_height_850hPa_member02 { get; set; }
        public double?[]? geopotential_height_850hPa_member03 { get; set; }
        public double?[]? geopotential_height_850hPa_member04 { get; set; }
        public double?[]? geopotential_height_850hPa_member05 { get; set; }
        public double?[]? geopotential_height_850hPa_member06 { get; set; }
        public double?[]? geopotential_height_850hPa_member07 { get; set; }
        public double?[]? geopotential_height_850hPa_member08 { get; set; }
        public double?[]? geopotential_height_850hPa_member09 { get; set; }
        public double?[]? geopotential_height_850hPa_member10 { get; set; }
        public double?[]? geopotential_height_850hPa_member11 { get; set; }
        public double?[]? geopotential_height_850hPa_member12 { get; set; }
        public double?[]? geopotential_height_850hPa_member13 { get; set; }
        public double?[]? geopotential_height_850hPa_member14 { get; set; }
        public double?[]? geopotential_height_850hPa_member15 { get; set; }
        public double?[]? geopotential_height_850hPa_member16 { get; set; }
        public double?[]? geopotential_height_850hPa_member17 { get; set; }
        public double?[]? geopotential_height_850hPa_member18 { get; set; }
        public double?[]? geopotential_height_850hPa_member19 { get; set; }
        public double?[]? geopotential_height_850hPa_member20 { get; set; }
        public double?[]? geopotential_height_500hPa { get; set; }
        public double?[]? geopotential_height_500hPa_member01 { get; set; }
        public double?[]? geopotential_height_500hPa_member02 { get; set; }
        public double?[]? geopotential_height_500hPa_member03 { get; set; }
        public double?[]? geopotential_height_500hPa_member04 { get; set; }
        public double?[]? geopotential_height_500hPa_member05 { get; set; }
        public double?[]? geopotential_height_500hPa_member06 { get; set; }
        public double?[]? geopotential_height_500hPa_member07 { get; set; }
        public double?[]? geopotential_height_500hPa_member08 { get; set; }
        public double?[]? geopotential_height_500hPa_member09 { get; set; }
        public double?[]? geopotential_height_500hPa_member10 { get; set; }
        public double?[]? geopotential_height_500hPa_member11 { get; set; }
        public double?[]? geopotential_height_500hPa_member12 { get; set; }
        public double?[]? geopotential_height_500hPa_member13 { get; set; }
        public double?[]? geopotential_height_500hPa_member14 { get; set; }
        public double?[]? geopotential_height_500hPa_member15 { get; set; }
        public double?[]? geopotential_height_500hPa_member16 { get; set; }
        public double?[]? geopotential_height_500hPa_member17 { get; set; }
        public double?[]? geopotential_height_500hPa_member18 { get; set; }
        public double?[]? geopotential_height_500hPa_member19 { get; set; }
        public double?[]? geopotential_height_500hPa_member20 { get; set; }
    }
}
